# Generated by Django 3.0.5 on 2020-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200415_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
