# Generated by Django 3.0.5 on 2020-04-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype',
            new_name='room_type',
        ),
    ]
