# Generated by Django 3.0.5 on 2020-04-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_auto_20200416_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.Room'),
        ),
    ]
